### ISSUE TITLE
Renaming "user" to "DNI (ID) / NIE"

### ISSUE THREAD

**Issue by es20490446e** [VBelles/bicicas-app#13]
The Bicicas website calls the user "DNI (ID) / NIE", where this app calls it "user".

This creates a small usability problem, where you can't really recall what that "user" was.

**Comment by VBelles** [comment]
Hello @es20490446e, sorry for the late answer, I understand that this is not ideal from user experience, but even that the credentials introduced by user are never stored and they are used to authenticate the user with the Bicicas API, I want to be cautelaos on which information I request from user.
I know this might make no sense without more context (there is an history related to this), but I prefer to leave to the user the responsibility of which information they input to the app.

**Comment by es20490446e** [comment]
[It doesn't matter](https://signalvnoise.com/archives2/it_just_doesnt_matter.php).

A potential attacker will know it is the DNI anyway, because it is mentioned in the website and the user profile. Along with plenty of other personal details.

**Comment by VBelles** [comment]
I understand your point, sorry I did not explain better myself. The problem is not about attackers nor security vulnerabilities, it is about strict policies on the stores and other boring stuff, it is not the same requesting a generic "user" which can be some sort of anonymous than requesting a DNI which is personal information, even if this information is properly handled.

**Comment by es20490446e** [comment]
Ah, I see.

Maybe something that subtly suggests it is the DNI, but doesn't explicitly state it, could do it.
